### ISSUE TITLE
cannot import "get_config()" from "config"

### ISSUE THREAD

**Issue by juliadietlmeier** [ChongQingNoSubway/SelfReg-UNet#4]
Hi, thank you for your work. I am trying to train on Synapse dataset but having difficulty with one of the required packages. ImportError: cannot import name 'get_config' from 'config' (/home/.conda/envs/sigpy_env/lib/python3.9/site-packages/config/__init__.py). Is there a certain "config" version that I need to install? Just installing with "pip install config" does not work. Thank you!

**Comment by xiwenc1** [comment]
Hi, it seems we missed some files, and after we uploaded them, this error should be fixed now.
