### ISSUE TITLE
3D KD_Loss

### ISSUE THREAD

**Issue by wakakaFF** [ChongQingNoSubway/SelfReg-UNet#7]
Thanks for your work!

I want to use it in 3D segmentation,  so I made some changes to the code, but the experiment didn't improve much.

Is there anything in my code that hasn't been changed?

![3c246b6f2d4a6c17087540d0cf0c04e](https://github.com/user-attachments/assets/58fc9406-8469-4af6-8ef2-382b756b39e3)
![f932ea1b26609f0cde5a67a35959058](https://github.com/user-attachments/assets/d8f20fc1-db2b-4a7f-a202-e9347db2e413)

**Comment by ChongQingNoSubway** [comment]
Thanks for being interested. 
The inter_fd calculation should include features from the encoder parts, and the decoders need to consider the different blocks at each stage (e.g., Each downsample stage has two transformer blocks SwimUnet ).
