### ISSUE TITLE
environment

### ISSUE THREAD

**Issue by bklee1213** [ChongQingNoSubway/SelfReg-UNet#8]
Can you tell me the environment in which the code will run and the version of the package?

**Comment by ChongQingNoSubway** [comment]
Please refer to the swin-Unet and CASCADE for the training environment. Our loss was implemented by pytorch without any extra packages.
https://github.com/HuCaoFighting/Swin-Unet 
https://github.com/SLDGroup/CASCADE

**Comment by bklee1213** [comment]
> Please refer to the swin-Unet and CASCADE for the training environment. Our loss was implemented by pytorch without any extra packages. https://github.com/HuCaoFighting/Swin-Unet https://github.com/SLDGroup/CASCADE

I encountered the following issues when using your test code. First, there was an error saying that the mask did not have a .shape attribute. I converted it to an array type with masks = np.array([lbl == i for i in range(1, classes)]), but then I encountered a second problem: an AssertionError occurred at assert image.shape[:2] == masks.shape[:2], stating that the image and mask should be of the same size.

**Comment by bklee1213** [comment]
> > Please refer to the swin-Unet and CASCADE for the training environment. Our loss was implemented by pytorch without any extra packages. https://github.com/HuCaoFighting/Swin-Unet https://github.com/SLDGroup/CASCADE
> 
> I encountered the following issues when using your test code. First, there was an error saying that the mask did not have a .shape attribute. I converted it to an array type with masks = np.array([lbl == i for i in range(1, classes)]), but then I encountered a second problem: an AssertionError occurred at assert image.shape[:2] == masks.shape[:2], stating that the image and mask should be of the same size.

**Comment by xiwenc1** [comment]
@bklee1213 May I know if you can successfully run the codes of Swin-Uet or TransUnet?

**Comment by bklee1213** [comment]
> @bklee1213 May I know if you can successfully run the codes of Swin-Uet or TransUnet?

yes,I can. I commented out the code and it was ready to run
